module.exports = {
    GRAMMAR_PERSONS,
    GRAMMAR_NUMBERS,
    NOT_SUPPORTED,
    PHRASAL_PART_TYPE,
    PRONOUN_BY_PERSON_NUMBER,
    POSSESSIVE_BY_PERSON_NUMBER,
    validateVerb,
    getOptExceptVerbMeanings,
    validPresentContPair,
    VerbBuilder,
    GrammarPerson,
    GrammarNumber,
    NounBuilder,
    PronounBuilder,
    SEPTIKS,
    AdjBuilder,
};