export {
    GRAMMAR_PERSONS,
    GRAMMAR_NUMBERS,
    PHRASAL_PART_TYPE,
    PART_EXPLANATION_TYPE,
    PRONOUN_BY_PERSON_NUMBER,
    POSSESSIVE_BY_PERSON_NUMBER,
    SEPTIKS,
    convertCyrillicToLatin20210128,
    convertLatin20210128ToCyrillic,
    validateVerb,
    getDeclAltInfo,
    getOptExceptVerbMeanings,
    validPresentContPair,
    NounBuilder,
    VerbBuilder,
}