/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasARun() {
        val classUnderTest = App()
        assertNotNull(classUnderTest::run, "app should have a greeting")
    }
}
