/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    fun run() {
        val verbBuilder = VerbBuilder("алу", false)
        for (person in GrammarPerson.entries) {
            for (number in GrammarNumber.entries) {
                val form = verbBuilder.presentTransitiveForm(person, number, SentenceType.Statement)
                println("- ${person}, ${number}: ${form.raw}")
            }
        }
    }
}

fun main() {
    App().run()
}
